env:
  TEST_TIME_FACTOR=500
dist: xenial
language: scala

jdk:
  - openjdk8

services:
  - redis-server

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt
    - $HOME/.coursier/cache

script: "sbt clean coverage +test"
after_success: "sbt coverageReport coveralls"
