env:
  TEST_TIME_FACTOR=100
dist: xenial
language: scala

jdk:
  - openjdk8

services:
  - redis-server

script:
  - export SBT_OPTS="${SBT_OPTS} -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -Xss2M"
  - sbt clean coverage +test
after_success: "sbt coverageReport coveralls"
